[
  {"lib/mix/tasks/product_attribute_claims.validate_backfill.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/product_attribute_claims.validate_backfill.ex",
   "Function Mix.Task.run/1 does not exist."},
  {"lib/mix/tasks/product_attribute_claims.validate_backfill.ex",
   "Function Mix.shell/0 does not exist."},
  {"lib/mix/tasks/product_attribute_claims.validate_backfill.ex",
   "Function Mix.raise/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_candidate_review_batch.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/product_compare.ingestion.cj_candidate_review_batch.ex",
   "Function Mix.raise/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_candidates.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/product_compare.ingestion.cj_candidates.ex",
   "Function Mix.raise/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_credentials.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/product_compare.ingestion.cj_credentials.ex",
   "Function Mix.raise/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_feeds.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/product_compare.ingestion.cj_feeds.ex", "Function Mix.raise/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_feeds.ex",
   "Function Mix.Task.run/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_import.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/product_compare.ingestion.cj_import.ex",
   "Function Mix.Task.run/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_import.ex",
   "Function Mix.raise/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_readiness_gate.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/product_compare.ingestion.cj_readiness_gate.ex",
   "Function Mix.raise/1 does not exist."},
  {"lib/mix/tasks/product_compare.ingestion.cj_runs.ex",
   "Callback info about the Mix.Task behaviour is not available."},
  {"lib/mix/tasks/product_compare.ingestion.cj_runs.ex", "Function Mix.raise/1 does not exist."},
  {"lib/product_compare/accounts.ex",
   "The pattern variable __password@1 can never match the type, because it is covered by previous clauses."},
  {"lib/product_compare/accounts.ex",
   "The pattern pattern <_query@1, __status@1, __now@1> can never match the type, because it is covered by previous clauses."},
  {"lib/product_compare/catalog.ex", "Type mismatch in call without opaque term in insert."},
  {"lib/product_compare/ingestion.ex",
   "The pattern variable _error@1 can never match the type, because it is covered by previous clauses."},
  {"lib/product_compare/ingestion/sources/cj/product_parser.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/product_compare/mix_tasks/cli_options.ex", "Function Mix.raise/1 does not exist."},
  {"lib/product_compare/mix_tasks/repo_only_startup.ex",
   "Function Mix.Task.run/1 does not exist."},
  {"lib/product_compare/mix_tasks/repo_only_startup.ex", "Function Mix.raise/1 does not exist."},
  {"lib/product_compare/mix_tasks/repo_only_startup.ex", "Function Mix.env/0 does not exist."},
  {"lib/product_compare/specs.ex",
   "The @spec for filterable_enum_option_pairs has an opaque subtype which is violated by the success typing."},
  {"lib/product_compare/specs.ex", "Type mismatch in call without opaque term in insert."},
  {"lib/product_compare/specs.ex", "Type mismatch in call without opaque term in run."},
  {"lib/product_compare/taxonomy.ex", "Type mismatch in call without opaque term in insert."},
  {"lib/product_compare/taxonomy.ex", "Type mismatch in call without opaque term in update."},
  {"lib/product_compare_schemas/discussions/thread_post.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/product_compare_schemas/discussions/thread_post.ex",
   "Type mismatch in call with opaque term in parent_chain_contains_id?."},
  {"lib/product_compare_web/plugs/fetch_current_user.ex", "The guard clause can never succeed."},
  {"lib/product_compare_web/plugs/require_same_origin.ex",
   "Type mismatch in call without opaque term in to_string."},
  {"lib/product_compare_web/plugs/require_same_origin.ex",
   "Type mismatch in call with opaque term in normalize_default_port."},
  {"lib/product_compare_web/resolvers/catalog_resolver.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/product_compare_web/runtime_config.ex",
   "Type mismatch in call without opaque term in to_string."},
  {"test/support/conn_case.ex", "Function ExUnit.Callbacks.__merge__/4 does not exist."},
  {"test/support/conn_case.ex", "Function ExUnit.Callbacks.__noop__/0 does not exist."},
  {"test/support/conn_case.ex", "Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/support/conn_case.ex", "Type mismatch in call without opaque term in to_string."},
  {"test/support/data_case.ex", "Function ExUnit.Callbacks.__merge__/4 does not exist."},
  {"test/support/data_case.ex", "Function ExUnit.Callbacks.__noop__/0 does not exist."},
  {"test/support/data_case.ex", "Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"test/support/data_case.ex", "Function ExUnit.Callbacks.on_exit/1 does not exist."}
]
